version: "3.8"

services:
  ylab-hackathon-db:
    image: postgres:16
    container_name: ylab-hackathon-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Europe/Paris
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ylab-hackathon-server:
    build:
      context: .
    restart: unless-stopped
    container_name: ylab-hackathon-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ylab-hackathon-db

volumes:
  postgres_data:
